### ISSUE TITLE
Minor documentation corrections

### ISSUE THREAD

**Issue by SnowLeopard71** [ryanfox1985/OctoPrint-Youtube-Timelapse#10]
Thanks for this plugin -- it still hasn't uploaded the first video yet, but I noticed couple minor documentation issues while doing the configuration.

In the prerequisites documentation, there are 2 references to _Google Drive_ and 1 to _Google Drive Backup_ that should be changed to _Youtube Data API_ for clarity.
https://github.com/ryanfox1985/OctoPrint-Youtube-Timelapse#create-a-google-oauth-app

Also, the first of the **_Prerequisites_** links on the plugins page (https://plugins.octoprint.org/plugins/youtube_timelapse/) is to https://github.com/jneilliii/OctoPrint-GoogleDriveBackup#create-a-google-oauth-app instead of this repo.

**Comment by ryanfox1985** [comment]
hello @SnowLeopard71 thanks for reporting, can you open a pull request fixing that?
