### ISSUE TITLE
[FR] Upload existing timelapses

### ISSUE THREAD

**Issue by lightmaster** [ryanfox1985/OctoPrint-Youtube-Timelapse#3]
Can you add an option to upload existing timelapses?

**Comment by ryanfox1985** [comment]
Hello, yes it could be nice to have this feature. Do you know where I can find documentation about where I can get the folder path where timelapse videos are stored?

**Comment by ryanfox1985** [comment]
not sure if it's always this path => `~/.octoprint/timelapse/*`

**Comment by lightmaster** [comment]
That's where mine are too

**Comment by ryanfox1985** [comment]
Shipped in this version: https://github.com/ryanfox1985/OctoPrint-Youtube-Timelapse/releases/tag/0.1.8

Have fun!
